### PR TITLE
Issue 80 createmodel

### PR DESCRIPTION
**Pull request by watchtheblur**
## What type of PR is this? (check all applicable)

- [ ] 🐛 Bug Fix
- [X] ✨ Feature (_**e.g.** API change, enhancement, addition, etc._)
- [ ] ♻️ Refactor
- [ ] 📝 Documentation
- [ ] 🔖 Release
- [ ] 🚩 Other (**concerning:**          )

## Context

Closes Issue #80 

This should be merged in after #81 

## Other Related Tickets & Documents (as needed)

This relates to Issue #79 

## Implementation Details

Installed osprojects model by editing models.py, and installed app by adding osprojects to base.py. Ran migrations for osprojects

docker-compose run --rm app python ./manage.py makemigrations osprojects
docker-compose run --rm app python ./manage.py migrate

## Any new migration files added?

- [X] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Did you add tests?
**_Code added or changed without test coverage or good reason for exemption won't be approved._**

- [ ] 👍 yes
- [ ] 🙋 no, because I need help
- [X] 🙅 no, because they aren't needed

## Did you add documentation?

- [ ] 📜 readme.md
- [ ] 📜 contributing.md
- [ ] 📜 wiki entry
- [ ] 🙋 I'd like someone to help write documentation, and will file a new issue for it
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by BethanyG** [comment]
@lpatmo  - should we be merging this?

**Comment by lpatmo** [comment]
Yep! Thought I already did, sorry!

**Comment by BethanyG** [comment]
@lpatmo  So I can't exactly revert this or it's associated change #81 -- but I **should**.  This PR should not have been approved - it is missing tests!!  So the next thing we need to make sure to do for this endpoint is add the tests in for this and for all other issues.  I was distracted.  But I won't be next time!!

**Comment by lpatmo** [comment]
lol, I didn't forget -- I honestly didn't think this PR needed tests, but then I looked up an example and it (kinda??) makes sense to me. I documented in https://github.com/codebuddies/backend/issues/179!

**Pull request merged**
