### PR TITLE
Folder restructuring - #30 and #31

### PR DESCRIPTION
**Pull request by lpatmo**
Addresses #30 and #31. 

(I also took a stab at #50, but renaming `cbv3_django_prototype` to `app`  everyone broke a lot of things -- so am holding off that for now. Will share screenshot of error messages in #50.) 

## Implementation
[x] Move all project files under the cbv3_django_prototype directory to the repository root
[x] Consider reorganizing the project, so that apps are created in the project root (rather than in the nested directory)
[x] Move all existing apps (namely, `resources`, `users`, and `userauth`) to the project root

Thanks @brylie for these suggestions, and @billglover and @BethanyG for reminding me I signed up to tackle them!

The app looks good (is still running heh) with these changes, so I shouldn't have broken anything. Please let me know if you noticed that I missed something.

### CODE REVIEW

**Comment by BethanyG** [comment]
I've probably pulled this incorrectly, but Django won't start for me, and all tests are failing under this structure.  Thoughts?

**Comment by lpatmo** [comment]
@BethanyG Can you share a screenshot of the error messages you're getting?

When I checked out this branch again after being in `master` everything was fine, but then I did `docker-compose down` anew and `docker-compose up --build` and saw this error:

image

:(

**Comment by lpatmo** [comment]
Earlier I'd thought I was only getting that after changing the top-most folder name to `app`, but maybe the issue started earlier...

**Comment by BethanyG** [comment]
Apologies.  Just getting back to this.  Yup.  That's the same error I am getting:

image

**Comment by brylie** [comment]
Make sure the `users` app is configured correctly in settings.py and that Django is finding the settings files after the shuffle :-)

**Comment by lpatmo** [comment]
@brylie Thanks! Do you have a good understanding of what needs to happen in (what I assume) `config/settings/base.py`? Am still having trouble debugging this issue: ```django.core.exceptions.ImproperlyConfigured: Cannot import 'cbv3_django_prototype.users'. Check that 'users.apps.UsersConfig.name' is correct.```

**Comment by brylie** [comment]
Do a project-wide search for `cbv3_django_prototype` to see if there are any files where it is still being used, such as for imports. 

I'll see if I can find a more detailed guide to renaming the core folder.

**Comment by brylie** [comment]
To reduce confusion, the `backend/cbv3_django_prototype/cbv3_django_prototype` folder can be renamed to something like `backend/cbv3_django_prototype/core`. Renaming it to `app` would be confusing to developers since in Django ["Applications" means something different](https://docs.djangoproject.com/en/3.0/ref/applications/#projects-and-applications) than the configuration directory we are renaming.

Double-check the following files:

## wsgi.py
https://github.com/codebuddies/backend/blob/7fb330ab2c6906c0c43178633ceac4e77ca1cba7/cbv3_django_prototype/config/wsgi.py#L26

## settings.py
https://github.com/codebuddies/backend/blob/7fb330ab2c6906c0c43178633ceac4e77ca1cba7/cbv3_django_prototype/config/settings/base.py#L10

https://github.com/codebuddies/backend/blob/7fb330ab2c6906c0c43178633ceac4e77ca1cba7/cbv3_django_prototype/config/settings/base.py#L99
## manage.py
https://github.com/codebuddies/backend/blob/7fb330ab2c6906c0c43178633ceac4e77ca1cba7/cbv3_django_prototype/manage.py#L28

**Comment by brylie** [comment]
@lpatmo I opened a pull request for your branch.

https://github.com/codebuddies/backend/pull/89

Would you please test those changes?

**Comment by billglover** [comment]
Is this still on hold or can I remove the `hold` tag and open this one up for merging in?

**Comment by BethanyG** [comment]
I'd like to hold this for a bit more, since we've already begun work on both a `projects` endpoint and the centralization of tagging code.  Suspect that merging this will require a "blow away and re-do" for those who have old trees, so want to make sure pending code changes are all checked in and re-worked beforehand.

**Comment by lpatmo** [comment]
> Suspect that merging this will require a "blow away and re-do" for those who have old trees

Yes, am afraid of that happening, since I had to do blow away the repo to see it working!

I'm wondering if we can merge this in after tags and before additional work on the `projects` endpoint, though, since I mainly proposed `projects` so @bkbuilt could have something to start tackling. Do you have an issue with a good stopping point there, @bkbuilt?

**Comment by brylie** [comment]
At the worst, it should only be necessary to delete and then check out the `master` branch locally. In general, since Git was tracking the structural changes they should be applied when people `pull` the master branch. They may also want to merge changes from `master` into any working branches.

**Comment by brylie** [comment]
Another thing is that the new `tags` app can simply be placed in the project folder while in development. That way the changes are already in the correct location.

**Comment by BethanyG** [comment]
@lpatmo - do we want to hold work and bite the bullet now that **tags** is merged in?  I was going to start work on some testing related issues, but we should get this piece done first, I think.

**Comment by lpatmo** [comment]
@BethanyG I will work on this asap (tonight or tomorrow); thanks for reminding me! And also for merging in https://github.com/codebuddies/backend/pull/96 🎉

**Comment by lpatmo** [comment]
There were a couple of conflicts here, and in the process of solving it I found it easier to create a new PR here: https://github.com/codebuddies/backend/pull/99

The new PR should include both Brylie and Bethany's changes. 

If someone would be so kind as to check out the `issues-30-31-file-reorg-part-2` branch from https://github.com/codebuddies/backend/pull/99 and double check that it runs and approve it, I would be grateful! Thank you!

**Comment by lpatmo** [comment]
Update: I've merged in PR#99. Thanks again @brylie for your commits! :)

**Pull request closed without merging**
