### PR TITLE
chore: Add Ansible, molecule and pytest-bdd

### PR DESCRIPTION
**Pull request by tgrrr**
## What

- Add ansible
- Add molecule
- Add pytest-bdd
- to requirements/local.txt

## Why

- To run migrations with Ansible
- To test Ansible with molecule
- To write BDD (Behaviour Driven Development) and TDD
- To Add BDD to codebuddies backend
- A separate PR to be available to multiple tickets

## What type of PR is this? (check all applicable)

- [x] ✨ Feature (_**e.g.** API change, enhancement, addition, etc._)
- [x] 🚩 Other (chore **concerning:**  )

## Context

Add ansible, pytest-bdd, and mocule 

Eg. for ticket https://github.com/codebuddies/backend/issues/111 _[User Registration] Make email required on backend #111_

The requirements are:

```
- [ ] Change the line in the model to make sure email is required
- [ ] Make migrations file and run migrations
- [ ] Add models test
- [ ] Make sure tests pass
```

### What was your thought process as you changed the code? 

Looking at the current issues for the MVP tagged
[P1 for MVP](https://github.com/codebuddies/backend/projects/1?card_filter_query=label%3A%22P1+for+MVP%22)

- We need to write clear, understandable tests for a number of tickets (ideally every ticket)
https://github.com/codebuddies/backend/issues/111, https://github.com/codebuddies/backend/issues/113, https://github.com/codebuddies/backend/issues/119 ...

BDD will help with that

- We need to include migrations. Hell, it's included in the template for this PR

Ansible and molecule will help with that

What does someone need to consider in reviewing it?

If there's any reason not to include Ansible
If we should use behave vs python-bdd

## New Libraries/Dependancies Introduced (Fill out as needed)

ansible==2.9.12             # https://github.com/ansible/ansible
pytest-bdd==3.4.0           # https://github.com/pytest-dev/pytest-bdd
molecule==3.0.8             # https://github.com/ansible-community/molecule

If you have added libraries or other dependancies, please list them (and links to their repos) below:

- [x] I've updated `requirements.txt`

## Any new migration files added?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed

## Did you add tests?
**_Code added or changed without test coverage or good reason for exemption won't be approved._**

- [ ] 👍 yes
- [ ] 🙋 no, because I need help
- [x] 🙅 no, because they aren't needed

## TODO: Did you add documentation?

- [x] 📜 readme.md
- [ ] 📜 contributing.md
- [ ] 📜 wiki entry
- [ ] 🙋 I'd like someone to help write documentation, and will file a new issue for it
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by BethanyG** [comment]
@tgrrr  -- Not convinced that Ansible gives us more than it adds in config and extra libraries to install.  Do you have links to articles/use cases I could look at?

We already test that migrations are present using GitHub Actions, so if that is the only use case at the moment for Ansible/molecule, I would pass -- or go with a purpose-build test package like [django-test-migrations](https://pypi.org/project/django-test-migrations/), should we need to test the application of migrations (roll forward/roll back/order of execution, etc). 

I also want to make sure that this setup is not "locking in" BDD - while it is a useful paradigm, it is not the _only_ paradigm - nor is it a one size fits all solution.  I do not want to get into a situation where tests already written will have to be re-written either in the BDD paradigm or vice-versa.  Anything we choose should be **compatible with Pytest/pytest-django as a test runner**, and interoperable with the other tests and frameworks we've used.  

From some looking around, it appears that Behave/behave-django and Behave/django-behave are **not** compatible with pytest as a test runner at all (pytest fails to discover tests).  So my preference would be for **pytest-bdd** -- but I'd like some concrete details on why that necessitates Ansible/molecule.

**Comment by tgrrr** [comment]
> Not convinced that Ansible gives us more than it adds in config and extra libraries to install. Do you have links to articles/use cases I could look at?

This is fairly simple, but I feel this is a good article https://developer.ibm.com/tutorials/d-bbd-guide-iac/

@BethanyG I might get @bengineerdavis to weigh in on this

My overall goal is to run tests across the entire application, including Docker. So, if someone new runs the setup, and something fails, it'll point them exactly (and hopefully clearly + explicitly) towards how to fix the problem.

> I also want to make sure that this setup is not "locking in" BDD - while it is a useful paradigm, it is not the only paradigm - nor is it a one size fits all solution. I do not want to get into a situation where tests already written will have to be re-written either in the BDD paradigm or vice-versa. Anything we choose should be compatible with Pytest/pytest-django as a test runner, and interoperable with the other tests and frameworks we've used.

I agree with all of this

> From some looking around, it appears that Behave/behave-django and Behave/django-behave are not compatible with pytest as a test runner at all (pytest fails to discover tests). So my preference would be for pytest-bdd -- but I'd like some concrete details on why that necessitates Ansible/molecule.

That sounds like an important discovery. Do you mind posting the sources?

Thanks,

Phil

**Comment by lpatmo** [comment]
> I also want to make sure that this setup is not "locking in" BDD - while it is a useful paradigm, it is not the only paradigm - nor is it a one size fits all solution. I do not want to get into a situation where tests already written will have to be re-written either in the BDD paradigm or vice-versa. Anything we choose should be compatible with Pytest/pytest-django as a test runner, and interoperable with the other tests and frameworks we've used.

Agree as well!

I do have a couple of followup questions:
- [ ] How does BDD help improve the developer experience?

> My overall goal is to run tests across the entire application, including Docker. So, if someone new runs the setup, and something fails, it'll point them exactly (and hopefully clearly + explicitly) towards how to fix the problem.

I've helped a couple of people get set up on the backend, and when there's a docker failure it's been either:
 - they're running a copy of Postgres on their machine at the same time and need to kill that process
 - something weird is happening with Docker for Windows and they need to reinstall / restart the computer
- There was a special Windows requirement with Python when running certain docker comands (e.g. @watchtheblur found and made a PR for it at https://github.com/codebuddies/backend/pull/147/files) 

In those cases, would the BDD tests help illuminate more details about what the user should be doing to resolve an issue? 

- [ ] Is the proposal that contributors who make PRs will need to write BDD tests as well as unit tests? 
- [ ] Where would the BDD tests live? And can you share an example of a test we would be writing for an existing feature?

Thanks!

**Comment by BethanyG** [comment]
@tgrrr After reading through the article, it seems that Ansible is providing infrastructure for _provisioning servers_.   While that may be useful for deployment, and for _integration testing_ in a staging environment (which for us will be one or more Digital Ocean Droplets), we are talking here about a development environment and the writing/running of _**unit tests**_ for  backend and API code.  

Ansible might help me provision a droplet on DO so that I can deploy the "stack" and make sure I got the process correct  -- but it will do nothing for me in troubleshooting docker permission problems on localhost for when I need to talk to the DB, nor is it useful in diagnosing a missing registration in the Django Admin app, or a serialization error. It also adds several additional layers of things (playbooks, YAML, supporting libraries) for newcomers to learn on top of an already complex-feeling stack.  

I am not saying it won't be useful in an integration testing/QA/deployment toolchain -- I am saying we are not at the stage of writing integration tests.  Right now, we need to make sure everyone writing code for the application writes proper uint tests for that code - and that those unit tests are as easy as possible to think through, make, and run.  

here are some of the articles/SO posts on BDD I've scanned through.  I put particular emphasis on Automation Panda, since his "shtick" is Python-flavored test automation.  
- [Automation Panda:  Python Testing 101: Behave](https://automationpanda.com/2018/05/11/python-testing-101-behave/)
- [Automation Panda: Python Testing 101:  Pytest-BDD](https://automationpanda.com/2018/10/22/python-testing-101-pytest-bdd/)
- [Automation Panda: Python BD Framework Comparison](https://automationpanda.com/2019/04/02/python-bdd-framework-comparison/)
- [So Post on PyTest and Behave using two different test runners](https://stackoverflow.com/questions/41146633/python-how-to-integrate-behave-into-pytest)
- [Behave Docs](https://behave.readthedocs.io/en/latest/usecase_django.html) -- these clearly state that the Django flavors use their own test runners.  One uses a special app, the other modifies Djangos built-in test runner via monkey-patching.  Neither integrates with PyTest.  It can also be added as a manual fixture.

**Comment by bengineerdavis** [comment]
Hi everyone, I'm just catching up on this conversation.

It didn't occur to me we would be adding ansible into Main or for wider adoption just yet. Ansible was supposed to be a tool that @tgrrr and I were using for ourselves while working within the context of the Backend repository. Just to be clear--I have no intention of committing to a team-wide adoption of Ansible until we both had tried it, applied it, and had a wider discussion (and user tests) on it.

> Ansible might help me provision a droplet on DO so that I can deploy the "stack" and make sure I got the process correct -- but it will do nothing for me in troubleshooting docker permission problems on localhost for when I need to talk to the DB, nor is it useful in diagnosing a missing registration in the Django Admin app, or a serialization error. It also adds several additional layers of things (playbooks, YAML, supporting libraries) for newcomers to learn on top of an already complex-feeling stack.

Ansible can also help you set up your local development environment, and could be valuable for automating the dev prerequisites needed for new and less experience devs to get "up and running". There's extensive support for docker environments

**Comment by bengineerdavis** [comment]
My intent for this exercise is to focus on unit tests. Pytest doesn't do integration tests very well, anyway--at least from what I've read.

Separately, I would strongly discourage Behave, because that is an entirely different testing suite than what we have: pytest-bdd at least guarantees that any tests can be maintained/recovered if we moved away from the bdd plugin, because the test themselves should be regular pytest. My understanding is that BDD can be a good way to discover unit tests by deducing them from features and potential integration tests.

**Comment by lpatmo** [comment]
> Ansible was supposed to be a tool that @tgrrr and I were using for ourselves while working within the context of the Backend repository. 

Totally fine to explore as a personal project! :) 

In terms of product priorities, I think we should be focusing on a couple other things like getting API endpoints up (currently being explored in /projects in this tracking issue: https://github.com/codebuddies/backend/issues/79), email verification, etc.

**Comment by tgrrr** [comment]
I think there's 2 conversation threads going on here.

1. Ansible
2. BDD

I think the best solution is to split this into 2 PR's, any objections?

**Comment by tgrrr** [comment]
I think there's 2 conversation threads going on here.

1. Ansible
2. BDD

I think the best solution is to split this into 2 PR's, any objections?

**Comment by BethanyG** [comment]
I think the best course of action here would be to not check in Ansible/molecule at all, given that we are working on using GitHub Actions for deployment to DO at the moment (see Draft PR #176).  They can of course be used locally - but I don't think they're a priority for this project.  (see @lpatmo comment above).

For `pytest-bdd`, recommend that once a PR for an issue is developed and the tests written, it be included there.  From the note on #82, it looks like that's the one you're going to tackle?  We closed #111, because the authentication scheme we are using doesn't trigger off an email on the custom user model.  See comments there and on discussion number 178.

@lpatmo   Thoughts here?

**Comment by lpatmo** [comment]
> I think there's 2 conversation threads going on here.
> - Ansible
> - BDD

Good call out!

> I think the best course of action here would be to not check in Ansible/molecule at all, given that we are working on using GitHub Actions for deployment to DO at the moment (see Draft PR #176). They can of course be used locally - but I don't think they're a priority for this project. 

Agree -- but as I mentioned before, you're welcome to fork/continue exploring it personally if it's something you're interested in. 

Re: BDD -- I'm down to explore it since I've never written a backend BDD test before (I did read the links you shared!), and I still want to wrap my head around this question:
- [x] Where would the BDD tests live? And can you share an example of a test we would be writing for an existing feature?

Side note: ultimately it's great if we have good tooling, but I also worry about getting lost in the weeds of infrastructure shiny things/"best practices" vs. focusing on the getting API endpoints up, teaching (partly myself lol) and everyone how to write good tests, and a working prototype. :) Right now I see the `backend` priorities as being:
- [x] get auth cleaned up w/ verification supported (see: https://github.com/codebuddies/backend/discussions/178)
- [x] chronicle the replicable steps for setting up and testing new API endpoints to make it easy for new contributors to work on the API (see: sandbox tracking issue at https://github.com/codebuddies/backend/issues/79)
- [x] deployment using github actions / docker / digitalocean (see: https://github.com/codebuddies/backend/discussions/177)

**Comment by tgrrr** [comment]
Lets delete this PR @lpatmo

**Comment by lpatmo** [comment]
(Note: generally, feel free to close PRs you open! Don't need my permission to close a PR you've created :))

**Pull request closed without merging**
